feat: group
le-pp2402/learnvocabulary pull request #7
Opened 2024-07-01 09:16 UTC by le-pp2402

2024-07-02 08:08 UTC, NVDinh2003 reviewed
check

2024-07-02 08:08 UTC, NVDinh2003 commented on learnvocabulary/src/main/java/com/phatpl/learnvocabulary/LearnVocabulary.java
đúng không ri

2024-07-19 10:15 UTC, KreltTruong requested changes

2024-07-19 10:24 UTC, chauduu requested changes

2024-07-23 07:18 UTC, le-pp2402 commented on learnvocabulary/src/main/java/com/phatpl/learnvocabulary/repositories/GroupRepository.java
> +    @Query(value = "SELECT `groups`.*\n" +
bữa PR#7 bị lỗi nên pphần này em sửa ở PR#8 luôn ạ, anh review lại cho em với
https://github.com/le-pp2402/learnvocabulary/pull/8/files

2024-07-23 07:19 UTC, le-pp2402 commented on learnvocabulary/src/main/java/com/phatpl/learnvocabulary/services/BaseService.java
> +    public Integer extractUserId(JwtAuthenticationToken jwtAuth) {
Dạ phần này em sửa ở PR#8 luôn ạ, chị review lại cho em với ạ 
https://github.com/le-pp2402/learnvocabulary/pull/8/files

2024-07-23 07:23 UTC, closed without merging